version: '3.9'

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - $PWD/my:/etc/mysql/conf.d
      - $PWD/sqlscripts:/docker-entrypoint-initdb.d
    networks:
      - tutorial

#  usersvc:
#    container_name: usersvc
#    build:
#      context: .
#    environment:
#      - GDD_BANNER=off
#      - GDD_PORT=6060
#      - DB_HOST=db
#    expose:
#      - "6060"
#    ports:
#      - "6060:6060"
#    networks:
#      - tutorial
#    depends_on:
#      - db

networks:
  tutorial:
    driver: bridge