apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: usersvc-statefulset
spec:
  selector:
    matchLabels:
      app: usersvc
  serviceName: usersvc-svc-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: usersvc
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: usersvc
          image: wubin1989/wordcloud_usersvc:v20220226171158
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: usersvc-svc-headless
spec:
  selector:
    app: usersvc
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  clusterIP: None