apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersvc
  template:
    metadata:
      labels:
        app: usersvc
    spec:
      containers:
        - name: usersvc
          image: wubin1989/wordcloud_usersvc:v20220226171158
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: usersvc-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: usersvc
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060