/**
* Generated by go-doudou v1.2.4.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	ddmodel "github.com/unionj-cloud/go-doudou/framework/http/model"
)

type HelloworldHandler interface {
	Greeting(w http.ResponseWriter, r *http.Request)
	Bye(w http.ResponseWriter, r *http.Request)
	BiStream(w http.ResponseWriter, r *http.Request)
	ClientStream(w http.ResponseWriter, r *http.Request)
	ServerStream(w http.ResponseWriter, r *http.Request)
}

func Routes(handler HelloworldHandler) []ddmodel.Route {
	return []ddmodel.Route{
		{
			"Greeting",
			"POST",
			"/greeting",
			handler.Greeting,
		},
		{
			"Bye",
			"POST",
			"/bye",
			handler.Bye,
		},
		{
			"BiStream",
			"POST",
			"/bi/stream",
			handler.BiStream,
		},
		{
			"ClientStream",
			"POST",
			"/client/stream",
			handler.ClientStream,
		},
		{
			"ServerStream",
			"POST",
			"/server/stream",
			handler.ServerStream,
		},
	}
}

var RouteAnnotationStore = ddmodel.AnnotationStore{}
