/**
* Generated by go-doudou v2.1.4.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type ComponentBHandler interface {
	Greeting(w http.ResponseWriter, r *http.Request)
}

func Routes(handler ComponentBHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "Greeting",
			Method:      "POST",
			Pattern:     "/greeting",
			HandlerFunc: handler.Greeting,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}
