apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordcloudseg-statefulset
spec:
  selector:
    matchLabels:
      app: wordcloudseg
  serviceName: wordcloudseg-svc-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: wordcloudseg
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: wordcloudseg
          image: wubin1989/wordcloud_wordcloudseg:v20220226170646
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wordcloudseg-svc-headless
spec:
  selector:
    app: wordcloudseg
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  clusterIP: None