apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcloudseg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordcloudseg
  template:
    metadata:
      labels:
        app: wordcloudseg
    spec:
      containers:
        - name: wordcloudseg
          image: wubin1989/wordcloud_wordcloudseg:v20220226170646
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wordcloudseg-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: wordcloudseg
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060