//*
// Generated by go-doudou v2.1.5.
// Don't edit!
//
// Version No.: v20230814

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: transport/grpc/componentb.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteUserIdRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUserIdRpcRequest) Reset() {
	*x = DeleteUserIdRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_componentb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserIdRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserIdRpcRequest) ProtoMessage() {}

func (x *DeleteUserIdRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_componentb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserIdRpcRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserIdRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_componentb_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteUserIdRpcRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GddUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Dept  string `protobuf:"bytes,4,opt,name=dept,proto3" json:"dept,omitempty"`
}

func (x *GddUser) Reset() {
	*x = GddUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_componentb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GddUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GddUser) ProtoMessage() {}

func (x *GddUser) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_componentb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GddUser.ProtoReflect.Descriptor instead.
func (*GddUser) Descriptor() ([]byte, []int) {
	return file_transport_grpc_componentb_proto_rawDescGZIP(), []int{1}
}

func (x *GddUser) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GddUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GddUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GddUser) GetDept() string {
	if x != nil {
		return x.Dept
	}
	return ""
}

type GetUserIdRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserIdRpcRequest) Reset() {
	*x = GetUserIdRpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_componentb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserIdRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdRpcRequest) ProtoMessage() {}

func (x *GetUserIdRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_componentb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdRpcRequest.ProtoReflect.Descriptor instead.
func (*GetUserIdRpcRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_componentb_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserIdRpcRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Page result wrapper
type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items      []*anypb.Any `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page       int64        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size       int64        `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MaxPage    int64        `protobuf:"varint,4,opt,name=maxPage,proto3" json:"maxPage,omitempty"`
	TotalPages int64        `protobuf:"varint,5,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	Total      int64        `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Last       bool         `protobuf:"varint,7,opt,name=last,proto3" json:"last,omitempty"`
	First      bool         `protobuf:"varint,8,opt,name=first,proto3" json:"first,omitempty"`
	Visible    int64        `protobuf:"varint,9,opt,name=visible,proto3" json:"visible,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_componentb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_componentb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_transport_grpc_componentb_proto_rawDescGZIP(), []int{3}
}

func (x *Page) GetItems() []*anypb.Any {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Page) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Page) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Page) GetMaxPage() int64 {
	if x != nil {
		return x.MaxPage
	}
	return 0
}

func (x *Page) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Page) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Page) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *Page) GetFirst() bool {
	if x != nil {
		return x.First
	}
	return false
}

func (x *Page) GetVisible() int64 {
	if x != nil {
		return x.Visible
	}
	return 0
}

// Parameter struct
type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    string       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Size    string       `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort    string       `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Order   string       `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Fields  string       `protobuf:"bytes,5,opt,name=fields,proto3" json:"fields,omitempty"`
	Filters []*anypb.Any `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_componentb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_componentb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_transport_grpc_componentb_proto_rawDescGZIP(), []int{4}
}

func (x *Parameter) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *Parameter) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Parameter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *Parameter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Parameter) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *Parameter) GetFilters() []*anypb.Any {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PostUserRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int32 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PostUserRpcResponse) Reset() {
	*x = PostUserRpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_componentb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostUserRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserRpcResponse) ProtoMessage() {}

func (x *PostUserRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_componentb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserRpcResponse.ProtoReflect.Descriptor instead.
func (*PostUserRpcResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_componentb_proto_rawDescGZIP(), []int{5}
}

func (x *PostUserRpcResponse) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_transport_grpc_componentb_proto protoreflect.FileDescriptor

var file_transport_grpc_componentb_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x62, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x57, 0x0a, 0x07, 0x47, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x70, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xee, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x61, 0x78, 0x50, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d,
	0x61, 0x78, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x61, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65,
	0x22, 0xa5, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0xe0, 0x02, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0b, 0x50, 0x6f, 0x73,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x70, 0x63, 0x12, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x62, 0x2e, 0x47, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x1f, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x70, 0x63, 0x12, 0x1f,
	0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x62, 0x2e, 0x47, 0x64, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x70, 0x63, 0x12, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x62, 0x2e,
	0x47, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x4d, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52,
	0x70, 0x63, 0x12, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x36,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x70, 0x63, 0x12, 0x15, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x6f, 0x64, 0x6f, 0x75, 0x64,
	0x6f, 0x75, 0x77, 0x6f, 0x72, 0x6b, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x62, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_grpc_componentb_proto_rawDescOnce sync.Once
	file_transport_grpc_componentb_proto_rawDescData = file_transport_grpc_componentb_proto_rawDesc
)

func file_transport_grpc_componentb_proto_rawDescGZIP() []byte {
	file_transport_grpc_componentb_proto_rawDescOnce.Do(func() {
		file_transport_grpc_componentb_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_grpc_componentb_proto_rawDescData)
	})
	return file_transport_grpc_componentb_proto_rawDescData
}

var file_transport_grpc_componentb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_transport_grpc_componentb_proto_goTypes = []interface{}{
	(*DeleteUserIdRpcRequest)(nil), // 0: componentb.DeleteUserIdRpcRequest
	(*GddUser)(nil),                // 1: componentb.GddUser
	(*GetUserIdRpcRequest)(nil),    // 2: componentb.GetUserIdRpcRequest
	(*Page)(nil),                   // 3: componentb.Page
	(*Parameter)(nil),              // 4: componentb.Parameter
	(*PostUserRpcResponse)(nil),    // 5: componentb.PostUserRpcResponse
	(*anypb.Any)(nil),              // 6: google.protobuf.Any
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_transport_grpc_componentb_proto_depIdxs = []int32{
	6, // 0: componentb.Page.items:type_name -> google.protobuf.Any
	6, // 1: componentb.Parameter.filters:type_name -> google.protobuf.Any
	1, // 2: componentb.ComponentbService.PostUserRpc:input_type -> componentb.GddUser
	2, // 3: componentb.ComponentbService.GetUserIdRpc:input_type -> componentb.GetUserIdRpcRequest
	1, // 4: componentb.ComponentbService.PutUserRpc:input_type -> componentb.GddUser
	0, // 5: componentb.ComponentbService.DeleteUserIdRpc:input_type -> componentb.DeleteUserIdRpcRequest
	4, // 6: componentb.ComponentbService.GetUsersRpc:input_type -> componentb.Parameter
	5, // 7: componentb.ComponentbService.PostUserRpc:output_type -> componentb.PostUserRpcResponse
	1, // 8: componentb.ComponentbService.GetUserIdRpc:output_type -> componentb.GddUser
	7, // 9: componentb.ComponentbService.PutUserRpc:output_type -> google.protobuf.Empty
	7, // 10: componentb.ComponentbService.DeleteUserIdRpc:output_type -> google.protobuf.Empty
	3, // 11: componentb.ComponentbService.GetUsersRpc:output_type -> componentb.Page
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transport_grpc_componentb_proto_init() }
func file_transport_grpc_componentb_proto_init() {
	if File_transport_grpc_componentb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_grpc_componentb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserIdRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_componentb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GddUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_componentb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserIdRpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_componentb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_componentb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_componentb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostUserRpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_grpc_componentb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_componentb_proto_goTypes,
		DependencyIndexes: file_transport_grpc_componentb_proto_depIdxs,
		MessageInfos:      file_transport_grpc_componentb_proto_msgTypes,
	}.Build()
	File_transport_grpc_componentb_proto = out.File
	file_transport_grpc_componentb_proto_rawDesc = nil
	file_transport_grpc_componentb_proto_goTypes = nil
	file_transport_grpc_componentb_proto_depIdxs = nil
}
