apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordcloudtask-statefulset
spec:
  selector:
    matchLabels:
      app: wordcloudtask
  serviceName: wordcloudtask-svc-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: wordcloudtask
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: wordcloudtask
          image: wubin1989/wordcloud_wordcloudtask:v20220226170923
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wordcloudtask-svc-headless
spec:
  selector:
    app: wordcloudtask
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  clusterIP: None