apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcloudtask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordcloudtask
  template:
    metadata:
      labels:
        app: wordcloudtask
    spec:
      containers:
        - name: wordcloudtask
          image: wubin1989/wordcloud_wordcloudtask:v20220226170923
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wordcloudtask-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: wordcloudtask
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060