/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package entity

import (
	"time"
)

//dd:table
type CommonLike struct {
	Id                  string     `dd:"pk;type:varchar(50);extra:comment '评论ID'"`
	RelateBusinessTable *string    `dd:"type:varchar(255);extra:comment '关联业务表'"`
	RelateBusinessId    *string    `dd:"type:varchar(50);extra:comment '关联业务ID'"`
	CreateTime          *time.Time `dd:"type:datetime;extra:comment '创建时间'"`
	CreateBy            *string    `dd:"type:varchar(50);extra:comment '创建人id'"`
	SysOrgCode          *string    `dd:"type:varchar(255);extra:comment '所属部门'"`
}
