/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package entity

import (
	"time"
)

//dd:table
type OrderMain struct {
	Id         string     `dd:"pk;type:varchar(36)"`
	CreateBy   *string    `dd:"type:varchar(50);extra:comment '创建人'"`
	CreateTime *time.Time `dd:"type:datetime;extra:comment '创建日期'"`
	UpdateBy   *string    `dd:"type:varchar(50);extra:comment '更新人'"`
	UpdateTime *time.Time `dd:"type:datetime;extra:comment '更新日期'"`
	SysOrgCode *string    `dd:"type:varchar(64);extra:comment '所属部门'"`
	OrderCode  *string    `dd:"type:varchar(32);extra:comment '订单编码'"`
	XdDate     *time.Time `dd:"type:datetime;extra:comment '下单时间'"`
	Money      *float64   `dd:"type:double;extra:comment '订单总额'"`
	Remark     *string    `dd:"type:varchar(500);extra:comment '备注'"`
}
