/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package entity

import (
	"time"
)

//dd:table
type OrderGoods struct {
	Id          string     `dd:"pk;type:varchar(36)"`
	CreateBy    *string    `dd:"type:varchar(50);extra:comment '创建人'"`
	CreateTime  *time.Time `dd:"type:datetime;extra:comment '创建日期'"`
	UpdateBy    *string    `dd:"type:varchar(50);extra:comment '更新人'"`
	UpdateTime  *time.Time `dd:"type:datetime;extra:comment '更新日期'"`
	SysOrgCode  *string    `dd:"type:varchar(64);extra:comment '所属部门'"`
	GoodName    *string    `dd:"type:varchar(32);extra:comment '商品名字'"`
	Price       *float64   `dd:"type:double;extra:comment '价格'"`
	Num         *int       `dd:"type:int(11);extra:comment '数量'"`
	ZongPrice   *float64   `dd:"type:double;extra:comment '单品总价'"`
	OrderMainId *string    `dd:"type:varchar(32);extra:comment '订单ID'"`
}
