/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package entity

import (
	"time"
)

//dd:table
type ReportShare struct {
	Id             string     `dd:"pk;type:varchar(32);extra:comment '主键'"`
	ReportId       *string    `dd:"type:varchar(32);extra:comment '在线excel设计器id'"`
	PreviewUrl     *string    `dd:"type:varchar(1000);extra:comment '预览地址'"`
	PreviewLock    *string    `dd:"type:varchar(4);extra:comment '密码锁'"`
	LastUpdateTime *time.Time `dd:"type:datetime;extra:comment '最后更新时间'"`
	TermOfValidity *string    `dd:"type:varchar(1);extra:comment '有效期(0:永久有效，1:1天，2:7天)'"`
	Status         *string    `dd:"type:varchar(1);extra:comment '是否过期(0未过期，1已过期)'"`
}
