/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package entity

import (
	"time"
)

//dd:table
type Report struct {
	Id         string     `dd:"pk;type:varchar(32);extra:comment '主键'"`
	Code       *string    `dd:"type:varchar(50);extra:comment '编码';unique:uniq_jmreport_code,1,asc"`
	Name       *string    `dd:"type:varchar(50);extra:comment '名称'"`
	Note       *string    `dd:"type:varchar(255);extra:comment '说明'"`
	Status     *string    `dd:"type:varchar(10);extra:comment '状态'"`
	Type       *string    `dd:"type:varchar(10);extra:comment '类型'"`
	JsonStr    *string    `dd:"type:text;extra:comment 'json字符串'"`
	ApiUrl     *string    `dd:"type:varchar(255);extra:comment '请求地址'"`
	Thumb      *string    `dd:"type:text;extra:comment '缩略图'"`
	CreateBy   *string    `dd:"type:varchar(50);extra:comment '创建人'"`
	CreateTime *time.Time `dd:"type:datetime;extra:comment '创建时间'"`
	UpdateBy   *string    `dd:"type:varchar(50);extra:comment '修改人'"`
	UpdateTime *time.Time `dd:"type:datetime;extra:comment '修改时间'"`
	DelFlag    *int8      `dd:"type:tinyint(1);extra:comment '删除标识0-正常,1-已删除'"`
	ApiMethod  *string    `dd:"type:varchar(255);extra:comment '请求方法0-get,1-post'"`
	ApiCode    *string    `dd:"type:varchar(255);extra:comment '请求编码'"`
	Template   *int8      `dd:"type:tinyint(1);extra:comment '是否是模板 0不是,1是'"`
	ViewCount  *int64     `dd:"type:bigint(20);extra:comment '浏览次数'"`
}
