/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package entity

import (
	"time"
)

//dd:table
type ReportDb struct {
	Id            string     `dd:"pk;type:varchar(36);extra:comment 'id'"`
	JimuReportId  *string    `dd:"type:varchar(32);extra:comment '主键字段'"`
	CreateBy      *string    `dd:"type:varchar(50);extra:comment '创建人登录名称'"`
	UpdateBy      *string    `dd:"type:varchar(50);extra:comment '更新人登录名称'"`
	CreateTime    *time.Time `dd:"type:datetime;extra:comment '创建日期'"`
	UpdateTime    *time.Time `dd:"type:datetime;extra:comment '更新日期'"`
	DbCode        *string    `dd:"type:varchar(32);extra:comment '数据集编码'"`
	DbChName      *string    `dd:"type:varchar(50);extra:comment '数据集名字'"`
	DbType        *string    `dd:"type:varchar(32);extra:comment '数据源类型'"`
	DbTableName   *string    `dd:"type:varchar(32);extra:comment '数据库表名'"`
	DbDynSql      *string    `dd:"type:longtext;extra:comment '动态查询SQL'"`
	DbKey         *string    `dd:"type:varchar(32);extra:comment '数据源KEY';index:idx_jmreportdb_db_key,1,asc"`
	TbDbKey       *string    `dd:"type:varchar(32);extra:comment '填报数据源'"`
	TbDbTableName *string    `dd:"type:varchar(32);extra:comment '填报数据表'"`
	JavaType      *string    `dd:"type:varchar(32);extra:comment 'java类数据集  类型（spring:springkey,class:java类名）'"`
	JavaValue     *string    `dd:"type:varchar(255);extra:comment 'java类数据源  数值（bean key/java类名）'"`
	ApiUrl        *string    `dd:"type:varchar(255);extra:comment '请求地址'"`
	ApiMethod     *string    `dd:"type:varchar(255);extra:comment '请求方法0-get,1-post'"`
	IsList        *int       `dd:"type:int(11);default:'0';extra:comment '是否是列表0否1是 默认0'"`
	IsPage        *string    `dd:"type:varchar(10);extra:comment '是否作为分页,0:不分页，1:分页'"`
	DbSource      *string    `dd:"type:varchar(255);extra:comment '数据源'"`
	DbSourceType  *string    `dd:"type:varchar(50);extra:comment '数据库类型 MYSQL ORACLE SQLSERVER'"`
	JsonData      *string    `dd:"type:text;extra:comment 'json数据，直接解析json内容'"`
	ApiConvert    *string    `dd:"type:varchar(255);extra:comment 'api转换器'"`
}
