/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package entity

import (
	"time"
)

//dd:table
type ShopType struct {
	Id         string     `dd:"pk;type:varchar(36)"`
	CreateBy   *string    `dd:"type:varchar(50);extra:comment '创建人'"`
	CreateTime *time.Time `dd:"type:datetime;extra:comment '创建日期'"`
	UpdateBy   *string    `dd:"type:varchar(50);extra:comment '更新人'"`
	UpdateTime *time.Time `dd:"type:datetime;extra:comment '更新日期'"`
	SysOrgCode *string    `dd:"type:varchar(64);extra:comment '所属部门'"`
	Name       *string    `dd:"type:varchar(32);extra:comment '分类名字'"`
	Content    *string    `dd:"type:varchar(200);extra:comment '描述'"`
	Pics       *string    `dd:"type:varchar(500);extra:comment '图片'"`
	Pid        *string    `dd:"type:varchar(32);extra:comment '父级节点'"`
	HasChild   *string    `dd:"type:varchar(3);extra:comment '是否有子节点'"`
}
