/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package entity

import (
	"time"
)

//dd:table
type SquareTaskKnowledge struct {
	Id          string     `dd:"pk;type:varchar(50);extra:comment '主键'"`
	TaskId      *string    `dd:"type:varchar(50);extra:comment '任务ID'"`
	KnowledgeId *string    `dd:"type:varchar(50);extra:comment '知识ID';index:knowledge_id,1,asc;fk:cad_knowledge,id,cad_square_task_knowledge_ibfk_1,ON DELETE CASCADE ON UPDATE RESTRICT"`
	CreateTime  *time.Time `dd:"type:datetime;extra:comment '创建时间'"`
}
