/**
* Generated by go-doudou v2.0.5.
* You can edit it as your need.
 */
package main

import (
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
	service "gormdemo"
	"gormdemo/config"
	"gormdemo/transport/httpsrv"
)

func main() {
	conf := config.LoadFromEnv()
	svc := service.NewGormdemo(conf)
	handler := httpsrv.NewGormdemoHandler(svc)
	srv := rest.NewRestServer()
	srv.AddRoute(httpsrv.Routes(handler)...)
	srv.Run()
}
