/**
* Generated by go-doudou v2.0.5.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type GormdemoHandler interface {
	PageUsers(w http.ResponseWriter, r *http.Request)
}

func Routes(handler GormdemoHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "PageUsers",
			Method:      "POST",
			Pattern:     "/page/users",
			HandlerFunc: handler.PageUsers,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{
	"PageUsers": {
		{
			Name: "@role",
			Params: []string{
				"admin",
			},
		},
	},
}
