apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helloworld-statefulset
spec:
  selector:
    matchLabels:
      app: helloworld
  serviceName: helloworld-svc-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: helloworld
          image: wubin1989/helloworld:v20221004215355
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc-headless
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  clusterIP: None