// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"fmt"
	"testgggorm2/config"

	"github.com/unionj-cloud/go-doudou/v2/toolkit/stringutils"
)

var TableNameBanner string

func init() {
	if stringutils.IsNotEmpty(config.G_Config.Db.Name) {
		TableNameBanner = fmt.Sprintf("%s.banner", config.G_Config.Db.Name)
	} else {
		TableNameBanner = "banner"
	}
}

// Banner mapped from table <banner>
type Banner struct {
	ID         int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:主键" json:"id,omitempty"` // 主键
	Title      *string `gorm:"column:title;type:varchar(50);comment:标题" json:"title,omitempty"`                     // 标题
	BannerType *int32  `gorm:"column:banner_type;type:tinyint(4);comment:类型" json:"bannerType,omitempty"`           // 类型
	BannerImg  *string `gorm:"column:banner_img;type:varchar(100);comment:图片地址" json:"bannerImg,omitempty"`         // 图片地址
	Link       *string `gorm:"column:link;type:varchar(200);comment:连接" json:"link,omitempty"`                      // 连接
	Sort       *int32  `gorm:"column:sort;type:int(10);comment:排序" json:"sort,omitempty"`                           // 排序
	Status     *int32  `gorm:"column:status;type:int(10);comment:状态" json:"status,omitempty"`                       // 状态
	AddTime    *int32  `gorm:"column:add_time;type:int(10);comment:添加时间" json:"addTime,omitempty"`                  // 添加时间
}

// TableName Banner's table name
func (*Banner) TableName() string {
	return TableNameBanner
}
