/**
* Generated by go-doudou v2.1.4.
* You can edit it as your need.
 */
package service

import "context"

//go:generate go-doudou svc http
//go:generate go-doudou svc grpc

type ComponentB interface {
	Greeting(ctx context.Context, msg string) (reply string, err error)
}
