/**
* Generated by go-doudou v2.0.1.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type WordcloudBffHandler interface {
	Upload(w http.ResponseWriter, r *http.Request)
	GetTaskPage(w http.ResponseWriter, r *http.Request)
}

func Routes(handler WordcloudBffHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "Upload",
			Method:      "POST",
			Pattern:     "/upload",
			HandlerFunc: handler.Upload,
		},
		{
			Name:        "GetTaskPage",
			Method:      "GET",
			Pattern:     "/task/page",
			HandlerFunc: handler.GetTaskPage,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}
