/**
* Generated by go-doudou v2.0.5.
* Don't edit!
 */
package client

import (
	"context"
	"go-doudou-tutorials/go-stats/vo"

	"github.com/go-resty/resty/v2"
	"github.com/shopspring/decimal"
)

type Options struct {
	GzipReqBody bool
}

type IGoStatsClient interface {
	LargestRemainder(ctx context.Context, _headers map[string]string, payload vo.PercentageReqVo, options Options) (_resp *resty.Response, data []vo.PercentageRespVo, err error)
	GetShelves_ShelfBooks_Book(ctx context.Context, _headers map[string]string, shelf int, book string, options Options) (_resp *resty.Response, data string, err error)
	GetBook(ctx context.Context, _headers map[string]string, price decimal.Decimal, options Options) (_resp *resty.Response, data string, err error)
}
