/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package dao

var commonconfigdaosql = `{{define "NoneZeroSet"}}
	{{- if .DelFlag}}
	` + "`" + `del_flag` + "`" + `=:del_flag,
	{{- end}}
	{{- if .Name}}
	` + "`" + `name` + "`" + `=:name,
	{{- end}}
	{{- if .Code}}
	` + "`" + `code` + "`" + `=:code,
	{{- end}}
	{{- if .Value}}
	` + "`" + `value` + "`" + `=:value,
	{{- end}}
	{{- if .DefaultValue}}
	` + "`" + `default_value` + "`" + `=:default_value,
	{{- end}}
	{{- if .ConfigDesc}}
	` + "`" + `config_desc` + "`" + `=:config_desc,
	{{- end}}
	{{- if .CreateTime}}
	` + "`" + `create_time` + "`" + `=:create_time,
	{{- end}}
	{{- if .CreateBy}}
	` + "`" + `create_by` + "`" + `=:create_by,
	{{- end}}
	{{- if .UpdateTime}}
	` + "`" + `update_time` + "`" + `=:update_time,
	{{- end}}
	{{- if .UpdateBy}}
	` + "`" + `update_by` + "`" + `=:update_by,
	{{- end}}
	{{- if .SysOrgCode}}
	` + "`" + `sys_org_code` + "`" + `=:sys_org_code,
	{{- end}}
{{end}}

{{define "InsertCommonConfig"}}
INSERT INTO ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
(
` + "`" + `id` + "`" + `,
` + "`" + `del_flag` + "`" + `,
` + "`" + `name` + "`" + `,
` + "`" + `code` + "`" + `,
` + "`" + `value` + "`" + `,
` + "`" + `default_value` + "`" + `,
` + "`" + `config_desc` + "`" + `,
` + "`" + `create_time` + "`" + `,
` + "`" + `create_by` + "`" + `,
` + "`" + `update_time` + "`" + `,
` + "`" + `update_by` + "`" + `,
` + "`" + `sys_org_code` + "`" + `)
VALUES (
	   :id,
	   :del_flag,
	   :name,
	   :code,
	   :value,
	   :default_value,
	   :config_desc,
	   :create_time,
	   :create_by,
	   :update_time,
	   :update_by,
	   :sys_org_code)
{{end}}

{{define "UpdateCommonConfig"}}
UPDATE ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
SET
	` + "`" + `del_flag` + "`" + `=:del_flag,
	` + "`" + `name` + "`" + `=:name,
	` + "`" + `code` + "`" + `=:code,
	` + "`" + `value` + "`" + `=:value,
	` + "`" + `default_value` + "`" + `=:default_value,
	` + "`" + `config_desc` + "`" + `=:config_desc,
	` + "`" + `create_time` + "`" + `=:create_time,
	` + "`" + `create_by` + "`" + `=:create_by,
	` + "`" + `update_time` + "`" + `=:update_time,
	` + "`" + `update_by` + "`" + `=:update_by,
	` + "`" + `sys_org_code` + "`" + `=:sys_org_code
WHERE
    ` + "`" + `id` + "`" + ` =:id
{{end}}

{{define "UpdateCommonConfigNoneZero"}}
UPDATE ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
SET
    {{Eval "NoneZeroSet" . | TrimSuffix ","}}
WHERE
    ` + "`" + `id` + "`" + `=:id
{{end}}

{{define "UpsertCommonConfig"}}
INSERT INTO ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
(
` + "`" + `id` + "`" + `,
` + "`" + `del_flag` + "`" + `,
` + "`" + `name` + "`" + `,
` + "`" + `code` + "`" + `,
` + "`" + `value` + "`" + `,
` + "`" + `default_value` + "`" + `,
` + "`" + `config_desc` + "`" + `,
` + "`" + `create_time` + "`" + `,
` + "`" + `create_by` + "`" + `,
` + "`" + `update_time` + "`" + `,
` + "`" + `update_by` + "`" + `,
` + "`" + `sys_org_code` + "`" + `)
VALUES (
        :id,
        :del_flag,
        :name,
        :code,
        :value,
        :default_value,
        :config_desc,
        :create_time,
        :create_by,
        :update_time,
        :update_by,
        :sys_org_code) ON DUPLICATE KEY
UPDATE
		` + "`" + `del_flag` + "`" + `=:del_flag,
		` + "`" + `name` + "`" + `=:name,
		` + "`" + `code` + "`" + `=:code,
		` + "`" + `value` + "`" + `=:value,
		` + "`" + `default_value` + "`" + `=:default_value,
		` + "`" + `config_desc` + "`" + `=:config_desc,
		` + "`" + `create_time` + "`" + `=:create_time,
		` + "`" + `create_by` + "`" + `=:create_by,
		` + "`" + `update_time` + "`" + `=:update_time,
		` + "`" + `update_by` + "`" + `=:update_by,
		` + "`" + `sys_org_code` + "`" + `=:sys_org_code
{{end}}

{{define "UpsertCommonConfigNoneZero"}}
INSERT INTO ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
(
` + "`" + `id` + "`" + `,
` + "`" + `del_flag` + "`" + `,
` + "`" + `name` + "`" + `,
` + "`" + `code` + "`" + `,
` + "`" + `value` + "`" + `,
` + "`" + `default_value` + "`" + `,
` + "`" + `config_desc` + "`" + `,
` + "`" + `create_time` + "`" + `,
` + "`" + `create_by` + "`" + `,
` + "`" + `update_time` + "`" + `,
` + "`" + `update_by` + "`" + `,
` + "`" + `sys_org_code` + "`" + `)
VALUES (
        :id,
        :del_flag,
        :name,
        :code,
        :value,
        :default_value,
        :config_desc,
        :create_time,
        :create_by,
        :update_time,
        :update_by,
        :sys_org_code) ON DUPLICATE KEY
UPDATE
		{{Eval "NoneZeroSet" . | TrimSuffix ","}}
{{end}}

{{define "GetCommonConfig"}}
select *
from ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
where ` + "`" + `id` + "`" + ` = ?
{{end}}

{{define "UpdateCommonConfigs"}}
UPDATE ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
SET
	` + "`" + `del_flag` + "`" + `=:del_flag,
	` + "`" + `name` + "`" + `=:name,
	` + "`" + `code` + "`" + `=:code,
	` + "`" + `value` + "`" + `=:value,
	` + "`" + `default_value` + "`" + `=:default_value,
	` + "`" + `config_desc` + "`" + `=:config_desc,
	` + "`" + `create_time` + "`" + `=:create_time,
	` + "`" + `create_by` + "`" + `=:create_by,
	` + "`" + `update_time` + "`" + `=:update_time,
	` + "`" + `update_by` + "`" + `=:update_by,
	` + "`" + `sys_org_code` + "`" + `=:sys_org_code
{{end}}

{{define "UpdateCommonConfigsNoneZero"}}
UPDATE ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
SET
    {{Eval "NoneZeroSet" . | TrimSuffix ","}}
{{end}}

{{define "InsertIgnoreCommonConfig"}}
INSERT IGNORE INTO ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_common_config` + "`" + `
(
` + "`" + `id` + "`" + `,
` + "`" + `del_flag` + "`" + `,
` + "`" + `name` + "`" + `,
` + "`" + `code` + "`" + `,
` + "`" + `value` + "`" + `,
` + "`" + `default_value` + "`" + `,
` + "`" + `config_desc` + "`" + `,
` + "`" + `create_time` + "`" + `,
` + "`" + `create_by` + "`" + `,
` + "`" + `update_time` + "`" + `,
` + "`" + `update_by` + "`" + `,
` + "`" + `sys_org_code` + "`" + `)
VALUES (
	   :id,
	   :del_flag,
	   :name,
	   :code,
	   :value,
	   :default_value,
	   :config_desc,
	   :create_time,
	   :create_by,
	   :update_time,
	   :update_by,
	   :sys_org_code)
{{end}}

{{define "UpdateClauseCommonConfig"}}
ON DUPLICATE KEY
UPDATE
		` + "`" + `del_flag` + "`" + `=VALUES(del_flag),
		` + "`" + `name` + "`" + `=VALUES(name),
		` + "`" + `code` + "`" + `=VALUES(code),
		` + "`" + `value` + "`" + `=VALUES(value),
		` + "`" + `default_value` + "`" + `=VALUES(default_value),
		` + "`" + `config_desc` + "`" + `=VALUES(config_desc),
		` + "`" + `create_time` + "`" + `=VALUES(create_time),
		` + "`" + `create_by` + "`" + `=VALUES(create_by),
		` + "`" + `update_time` + "`" + `=VALUES(update_time),
		` + "`" + `update_by` + "`" + `=VALUES(update_by),
		` + "`" + `sys_org_code` + "`" + `=VALUES(sys_org_code)
{{end}}

{{define "UpdateClauseSelectCommonConfig"}}
ON DUPLICATE KEY
UPDATE
		{{- range $i, $co := .Columns}}
		{{- if $i}},{{end}}
		` + "`" + `{{$co}}` + "`" + `=VALUES({{$co}})
		{{- end }}
{{end}}`
