/**
* Generated by go-doudou v2.0.4.
* You can edit it as your need.
 */
package dao

var squaretaskuserdaosql = `{{define "NoneZeroSet"}}
	{{- if .IsAssigned}}
	` + "`" + `is_assigned` + "`" + `=:is_assigned,
	{{- end}}
	{{- if .TaskId}}
	` + "`" + `task_id` + "`" + `=:task_id,
	{{- end}}
	{{- if .UserId}}
	` + "`" + `user_id` + "`" + `=:user_id,
	{{- end}}
	{{- if .CreateTime}}
	` + "`" + `create_time` + "`" + `=:create_time,
	{{- end}}
{{end}}

{{define "InsertSquareTaskUser"}}
INSERT INTO ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
(
` + "`" + `id` + "`" + `,
` + "`" + `is_assigned` + "`" + `,
` + "`" + `task_id` + "`" + `,
` + "`" + `user_id` + "`" + `,
` + "`" + `create_time` + "`" + `)
VALUES (
	   :id,
	   :is_assigned,
	   :task_id,
	   :user_id,
	   :create_time)
{{end}}

{{define "UpdateSquareTaskUser"}}
UPDATE ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
SET
	` + "`" + `is_assigned` + "`" + `=:is_assigned,
	` + "`" + `task_id` + "`" + `=:task_id,
	` + "`" + `user_id` + "`" + `=:user_id,
	` + "`" + `create_time` + "`" + `=:create_time
WHERE
    ` + "`" + `id` + "`" + ` =:id
{{end}}

{{define "UpdateSquareTaskUserNoneZero"}}
UPDATE ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
SET
    {{Eval "NoneZeroSet" . | TrimSuffix ","}}
WHERE
    ` + "`" + `id` + "`" + `=:id
{{end}}

{{define "UpsertSquareTaskUser"}}
INSERT INTO ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
(
` + "`" + `id` + "`" + `,
` + "`" + `is_assigned` + "`" + `,
` + "`" + `task_id` + "`" + `,
` + "`" + `user_id` + "`" + `,
` + "`" + `create_time` + "`" + `)
VALUES (
        :id,
        :is_assigned,
        :task_id,
        :user_id,
        :create_time) ON DUPLICATE KEY
UPDATE
		` + "`" + `is_assigned` + "`" + `=:is_assigned,
		` + "`" + `task_id` + "`" + `=:task_id,
		` + "`" + `user_id` + "`" + `=:user_id,
		` + "`" + `create_time` + "`" + `=:create_time
{{end}}

{{define "UpsertSquareTaskUserNoneZero"}}
INSERT INTO ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
(
` + "`" + `id` + "`" + `,
` + "`" + `is_assigned` + "`" + `,
` + "`" + `task_id` + "`" + `,
` + "`" + `user_id` + "`" + `,
` + "`" + `create_time` + "`" + `)
VALUES (
        :id,
        :is_assigned,
        :task_id,
        :user_id,
        :create_time) ON DUPLICATE KEY
UPDATE
		{{Eval "NoneZeroSet" . | TrimSuffix ","}}
{{end}}

{{define "GetSquareTaskUser"}}
select *
from ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
where ` + "`" + `id` + "`" + ` = ?
{{end}}

{{define "UpdateSquareTaskUsers"}}
UPDATE ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
SET
	` + "`" + `is_assigned` + "`" + `=:is_assigned,
	` + "`" + `task_id` + "`" + `=:task_id,
	` + "`" + `user_id` + "`" + `=:user_id,
	` + "`" + `create_time` + "`" + `=:create_time
{{end}}

{{define "UpdateSquareTaskUsersNoneZero"}}
UPDATE ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
SET
    {{Eval "NoneZeroSet" . | TrimSuffix ","}}
{{end}}

{{define "InsertIgnoreSquareTaskUser"}}
INSERT IGNORE INTO ` + "`" + `jeecg-boot` + "`" + `.` + "`" + `cad_square_task_user` + "`" + `
(
` + "`" + `id` + "`" + `,
` + "`" + `is_assigned` + "`" + `,
` + "`" + `task_id` + "`" + `,
` + "`" + `user_id` + "`" + `,
` + "`" + `create_time` + "`" + `)
VALUES (
	   :id,
	   :is_assigned,
	   :task_id,
	   :user_id,
	   :create_time)
{{end}}

{{define "UpdateClauseSquareTaskUser"}}
ON DUPLICATE KEY
UPDATE
		` + "`" + `is_assigned` + "`" + `=VALUES(is_assigned),
		` + "`" + `task_id` + "`" + `=VALUES(task_id),
		` + "`" + `user_id` + "`" + `=VALUES(user_id),
		` + "`" + `create_time` + "`" + `=VALUES(create_time)
{{end}}

{{define "UpdateClauseSelectSquareTaskUser"}}
ON DUPLICATE KEY
UPDATE
		{{- range $i, $co := .Columns}}
		{{- if $i}},{{end}}
		` + "`" + `{{$co}}` + "`" + `=VALUES({{$co}})
		{{- end }}
{{end}}`
