/**
* Generated by go-doudou v2.0.6.
* You can edit it as your need.
 */
package service

import (
	"context"
	"service-b/dto"
)

//go:generate go-doudou svc http -c
//go:generate go-doudou svc grpc

type ServiceB interface {
	GetDeptById(ctx context.Context, deptId int) (dept dto.DeptDto, err error)
}
