filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "go-doudou-wordcloud-filebeat"

logging.json: true
logging.metrics.enabled: false
