// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzCalendar = "qrtz_calendars"

// QrtzCalendar mapped from table <qrtz_calendars>
type QrtzCalendar struct {
	SCHEDNAME    *string `gorm:"column:SCHED_NAME;type:varchar(120)" json:"SCHED_NAME,omitempty"`
	CALENDARNAME *string `gorm:"column:CALENDAR_NAME;type:varchar(200)" json:"CALENDAR_NAME,omitempty"`
	CALENDAR     *[]byte `gorm:"column:CALENDAR;type:blob" json:"CALENDAR,omitempty"`
}

// TableName QrtzCalendar's table name
func (*QrtzCalendar) TableName() string {
	return TableNameQrtzCalendar
}
