// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCadCommonComment = "cad_common_comment"

// CadCommonComment mapped from table <cad_common_comment>
type CadCommonComment struct {
	ID                  string    `gorm:"column:id" json:"id"`
	DelFlag             int32     `gorm:"column:del_flag" json:"del_flag"`
	RelateBusinessTable string    `gorm:"column:relate_business_table" json:"relate_business_table"`
	RelateBusinessID    string    `gorm:"column:relate_business_id" json:"relate_business_id"`
	Content             string    `gorm:"column:content" json:"content"`
	ReplyTo             string    `gorm:"column:reply_to" json:"reply_to"`
	CreateTime          time.Time `gorm:"column:create_time" json:"create_time"`
	CreateBy            string    `gorm:"column:create_by" json:"create_by"`
	SysOrgCode          string    `gorm:"column:sys_org_code" json:"sys_org_code"`
}

// TableName CadCommonComment's table name
func (*CadCommonComment) TableName() string {
	return TableNameCadCommonComment
}
