// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzCronTrigger = "qrtz_cron_triggers"

// QrtzCronTrigger mapped from table <qrtz_cron_triggers>
type QrtzCronTrigger struct {
	SCHEDNAME      string `gorm:"column:SCHED_NAME" json:"SCHED_NAME"`
	TRIGGERNAME    string `gorm:"column:TRIGGER_NAME" json:"TRIGGER_NAME"`
	TRIGGERGROUP   string `gorm:"column:TRIGGER_GROUP" json:"TRIGGER_GROUP"`
	CRONEXPRESSION string `gorm:"column:CRON_EXPRESSION" json:"CRON_EXPRESSION"`
	TIMEZONEID     string `gorm:"column:TIME_ZONE_ID" json:"TIME_ZONE_ID"`
}

// TableName QrtzCronTrigger's table name
func (*QrtzCronTrigger) TableName() string {
	return TableNameQrtzCronTrigger
}
