// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzFiredTrigger = "qrtz_fired_triggers"

// QrtzFiredTrigger mapped from table <qrtz_fired_triggers>
type QrtzFiredTrigger struct {
	SCHEDNAME        string `gorm:"column:SCHED_NAME" json:"SCHED_NAME"`
	ENTRYID          string `gorm:"column:ENTRY_ID" json:"ENTRY_ID"`
	TRIGGERNAME      string `gorm:"column:TRIGGER_NAME" json:"TRIGGER_NAME"`
	TRIGGERGROUP     string `gorm:"column:TRIGGER_GROUP" json:"TRIGGER_GROUP"`
	INSTANCENAME     string `gorm:"column:INSTANCE_NAME" json:"INSTANCE_NAME"`
	FIREDTIME        int64  `gorm:"column:FIRED_TIME" json:"FIRED_TIME"`
	SCHEDTIME        int64  `gorm:"column:SCHED_TIME" json:"SCHED_TIME"`
	PRIORITY         int32  `gorm:"column:PRIORITY" json:"PRIORITY"`
	STATE            string `gorm:"column:STATE" json:"STATE"`
	JOBNAME          string `gorm:"column:JOB_NAME" json:"JOB_NAME"`
	JOBGROUP         string `gorm:"column:JOB_GROUP" json:"JOB_GROUP"`
	ISNONCONCURRENT  string `gorm:"column:IS_NONCONCURRENT" json:"IS_NONCONCURRENT"`
	REQUESTSRECOVERY string `gorm:"column:REQUESTS_RECOVERY" json:"REQUESTS_RECOVERY"`
}

// TableName QrtzFiredTrigger's table name
func (*QrtzFiredTrigger) TableName() string {
	return TableNameQrtzFiredTrigger
}
