apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gostats-statefulset
spec:
  selector:
    matchLabels:
      app: gostats
  serviceName: gostats-svc-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: gostats
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: gostats
          image: gostats
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gostats-svc-headless
spec:
  selector:
    app: gostats
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  clusterIP: None