apiVersion: apps/v1
kind: Deployment
metadata:
  name: gostats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gostats
  template:
    metadata:
      labels:
        app: gostats
    spec:
      containers:
        - name: gostats
          image: gostats
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gostats-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: gostats
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060