// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: transport/grpc/banana.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BananaServiceClient is the client API for BananaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BananaServiceClient interface {
	// You can define your service methods as your need. Below is an example.
	// You can also add annotations here like @role(admin) to add meta data to routes for
	// implementing your own middlewares
	PostUserRpc(ctx context.Context, in *GddUser, opts ...grpc.CallOption) (*PostUserRpcResponse, error)
	GetUserIdRpc(ctx context.Context, in *GetUserIdRpcRequest, opts ...grpc.CallOption) (*GddUser, error)
	PutUserRpc(ctx context.Context, in *GddUser, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteUserIdRpc(ctx context.Context, in *DeleteUserIdRpcRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUsersRpc(ctx context.Context, in *Parameter, opts ...grpc.CallOption) (*Page, error)
}

type bananaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBananaServiceClient(cc grpc.ClientConnInterface) BananaServiceClient {
	return &bananaServiceClient{cc}
}

func (c *bananaServiceClient) PostUserRpc(ctx context.Context, in *GddUser, opts ...grpc.CallOption) (*PostUserRpcResponse, error) {
	out := new(PostUserRpcResponse)
	err := c.cc.Invoke(ctx, "/banana.BananaService/PostUserRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) GetUserIdRpc(ctx context.Context, in *GetUserIdRpcRequest, opts ...grpc.CallOption) (*GddUser, error) {
	out := new(GddUser)
	err := c.cc.Invoke(ctx, "/banana.BananaService/GetUserIdRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) PutUserRpc(ctx context.Context, in *GddUser, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/banana.BananaService/PutUserRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) DeleteUserIdRpc(ctx context.Context, in *DeleteUserIdRpcRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/banana.BananaService/DeleteUserIdRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bananaServiceClient) GetUsersRpc(ctx context.Context, in *Parameter, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/banana.BananaService/GetUsersRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BananaServiceServer is the server API for BananaService service.
// All implementations must embed UnimplementedBananaServiceServer
// for forward compatibility
type BananaServiceServer interface {
	// You can define your service methods as your need. Below is an example.
	// You can also add annotations here like @role(admin) to add meta data to routes for
	// implementing your own middlewares
	PostUserRpc(context.Context, *GddUser) (*PostUserRpcResponse, error)
	GetUserIdRpc(context.Context, *GetUserIdRpcRequest) (*GddUser, error)
	PutUserRpc(context.Context, *GddUser) (*emptypb.Empty, error)
	DeleteUserIdRpc(context.Context, *DeleteUserIdRpcRequest) (*emptypb.Empty, error)
	GetUsersRpc(context.Context, *Parameter) (*Page, error)
	mustEmbedUnimplementedBananaServiceServer()
}

// UnimplementedBananaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBananaServiceServer struct {
}

func (UnimplementedBananaServiceServer) PostUserRpc(context.Context, *GddUser) (*PostUserRpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostUserRpc not implemented")
}
func (UnimplementedBananaServiceServer) GetUserIdRpc(context.Context, *GetUserIdRpcRequest) (*GddUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIdRpc not implemented")
}
func (UnimplementedBananaServiceServer) PutUserRpc(context.Context, *GddUser) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUserRpc not implemented")
}
func (UnimplementedBananaServiceServer) DeleteUserIdRpc(context.Context, *DeleteUserIdRpcRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserIdRpc not implemented")
}
func (UnimplementedBananaServiceServer) GetUsersRpc(context.Context, *Parameter) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersRpc not implemented")
}
func (UnimplementedBananaServiceServer) mustEmbedUnimplementedBananaServiceServer() {}

// UnsafeBananaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BananaServiceServer will
// result in compilation errors.
type UnsafeBananaServiceServer interface {
	mustEmbedUnimplementedBananaServiceServer()
}

func RegisterBananaServiceServer(s grpc.ServiceRegistrar, srv BananaServiceServer) {
	s.RegisterService(&BananaService_ServiceDesc, srv)
}

func _BananaService_PostUserRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GddUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).PostUserRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/banana.BananaService/PostUserRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).PostUserRpc(ctx, req.(*GddUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_GetUserIdRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIdRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).GetUserIdRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/banana.BananaService/GetUserIdRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).GetUserIdRpc(ctx, req.(*GetUserIdRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_PutUserRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GddUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).PutUserRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/banana.BananaService/PutUserRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).PutUserRpc(ctx, req.(*GddUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_DeleteUserIdRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserIdRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).DeleteUserIdRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/banana.BananaService/DeleteUserIdRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).DeleteUserIdRpc(ctx, req.(*DeleteUserIdRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BananaService_GetUsersRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Parameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BananaServiceServer).GetUsersRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/banana.BananaService/GetUsersRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BananaServiceServer).GetUsersRpc(ctx, req.(*Parameter))
	}
	return interceptor(ctx, in, info, handler)
}

// BananaService_ServiceDesc is the grpc.ServiceDesc for BananaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BananaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "banana.BananaService",
	HandlerType: (*BananaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostUserRpc",
			Handler:    _BananaService_PostUserRpc_Handler,
		},
		{
			MethodName: "GetUserIdRpc",
			Handler:    _BananaService_GetUserIdRpc_Handler,
		},
		{
			MethodName: "PutUserRpc",
			Handler:    _BananaService_PutUserRpc_Handler,
		},
		{
			MethodName: "DeleteUserIdRpc",
			Handler:    _BananaService_DeleteUserIdRpc_Handler,
		},
		{
			MethodName: "GetUsersRpc",
			Handler:    _BananaService_GetUsersRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/grpc/banana.proto",
}
