/**
* Generated by go-doudou v2.0.0.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type EnumDemoHandler interface {
	GetKeyboard(w http.ResponseWriter, r *http.Request)
	GetKeyboard2(w http.ResponseWriter, r *http.Request)
	GetKeyboards(w http.ResponseWriter, r *http.Request)
	GetKeyboards2(w http.ResponseWriter, r *http.Request)
	GetKeyboards5(w http.ResponseWriter, r *http.Request)
	Keyboard(w http.ResponseWriter, r *http.Request)
	Greeting(w http.ResponseWriter, r *http.Request)
	Greeting1(w http.ResponseWriter, r *http.Request)
}

func Routes(handler EnumDemoHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "GetKeyboard",
			Method:      "GET",
			Pattern:     "/keyboard",
			HandlerFunc: handler.GetKeyboard,
		},
		{
			Name:        "GetKeyboard2",
			Method:      "GET",
			Pattern:     "/keyboard/2",
			HandlerFunc: handler.GetKeyboard2,
		},
		{
			Name:        "GetKeyboards",
			Method:      "GET",
			Pattern:     "/keyboards",
			HandlerFunc: handler.GetKeyboards,
		},
		{
			Name:        "GetKeyboards2",
			Method:      "GET",
			Pattern:     "/keyboards/2",
			HandlerFunc: handler.GetKeyboards2,
		},
		{
			Name:        "GetKeyboards5",
			Method:      "GET",
			Pattern:     "/keyboards/5",
			HandlerFunc: handler.GetKeyboards5,
		},
		{
			Name:        "Keyboard",
			Method:      "POST",
			Pattern:     "/keyboard",
			HandlerFunc: handler.Keyboard,
		},
		{
			Name:        "Greeting",
			Method:      "POST",
			Pattern:     "/greeting",
			HandlerFunc: handler.Greeting,
		},
		{
			Name:        "Greeting1",
			Method:      "POST",
			Pattern:     "/greeting/1",
			HandlerFunc: handler.Greeting1,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}
