// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.

package dto

//go:generate go-doudou name --file $GOFILE

// QrtzCronTrigger mapped from table <qrtz_cron_triggers>
type QrtzCronTrigger struct {
	SCHEDNAME      *string `json:"sCHEDNAME"`
	TRIGGERNAME    *string `json:"tRIGGERNAME"`
	TRIGGERGROUP   *string `json:"tRIGGERGROUP"`
	CRONEXPRESSION *string `json:"cRONEXPRESSION"`
	TIMEZONEID     *string `json:"tIMEZONEID"`
}
