// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.

package dto

import (
	"time"
)

//go:generate go-doudou name --file $GOFILE

// TClient mapped from table <t_client>
type TClient struct {
	ID              int32      `json:"id"`
	Name            string     `json:"name"` // client name 客户端名称
	PublicKey       string     `json:"publicKey"`
	EncryptedSecret string     `json:"encryptedSecret"`
	CreateAt        *time.Time `json:"createAt"`
	UpdateAt        *time.Time `json:"updateAt"`
	DeleteAt        *time.Time `json:"deleteAt"`
}
