// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WordcloudSegServiceClient is the client API for WordcloudSegService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordcloudSegServiceClient interface {
	SegRpc(ctx context.Context, in *SegPayload, opts ...grpc.CallOption) (*SegResult, error)
}

type wordcloudSegServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWordcloudSegServiceClient(cc grpc.ClientConnInterface) WordcloudSegServiceClient {
	return &wordcloudSegServiceClient{cc}
}

func (c *wordcloudSegServiceClient) SegRpc(ctx context.Context, in *SegPayload, opts ...grpc.CallOption) (*SegResult, error) {
	out := new(SegResult)
	err := c.cc.Invoke(ctx, "/wordcloud_seg.WordcloudSegService/SegRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordcloudSegServiceServer is the server API for WordcloudSegService service.
// All implementations must embed UnimplementedWordcloudSegServiceServer
// for forward compatibility
type WordcloudSegServiceServer interface {
	SegRpc(context.Context, *SegPayload) (*SegResult, error)
	mustEmbedUnimplementedWordcloudSegServiceServer()
}

// UnimplementedWordcloudSegServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWordcloudSegServiceServer struct {
}

func (UnimplementedWordcloudSegServiceServer) SegRpc(context.Context, *SegPayload) (*SegResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SegRpc not implemented")
}
func (UnimplementedWordcloudSegServiceServer) mustEmbedUnimplementedWordcloudSegServiceServer() {}

// UnsafeWordcloudSegServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordcloudSegServiceServer will
// result in compilation errors.
type UnsafeWordcloudSegServiceServer interface {
	mustEmbedUnimplementedWordcloudSegServiceServer()
}

func RegisterWordcloudSegServiceServer(s grpc.ServiceRegistrar, srv WordcloudSegServiceServer) {
	s.RegisterService(&WordcloudSegService_ServiceDesc, srv)
}

func _WordcloudSegService_SegRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordcloudSegServiceServer).SegRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordcloud_seg.WordcloudSegService/SegRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordcloudSegServiceServer).SegRpc(ctx, req.(*SegPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// WordcloudSegService_ServiceDesc is the grpc.ServiceDesc for WordcloudSegService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordcloudSegService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wordcloud_seg.WordcloudSegService",
	HandlerType: (*WordcloudSegServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SegRpc",
			Handler:    _WordcloudSegService_SegRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/grpc/wordcloudseg.proto",
}
