apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordcloudbff-statefulset
spec:
  selector:
    matchLabels:
      app: wordcloudbff
  serviceName: wordcloudbff-svc-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: wordcloudbff
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: wordcloudbff
          image: wubin1989/wordcloud_wordcloudbff:v20220226165612
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wordcloudbff-svc-headless
spec:
  selector:
    app: wordcloudbff
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  clusterIP: None