apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcloudbff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordcloudbff
  template:
    metadata:
      labels:
        app: wordcloudbff
    spec:
      containers:
        - name: wordcloudbff
          image: wubin1989/wordcloud_wordcloudbff:v20220226165612
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 6060
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wordcloudbff-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: wordcloudbff
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060