{
 "title": "Go Runtime",
 "description": "Visualize metrics generated by https://github.com/tevjef/go-runtime-metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "show tag values from go_doudou_app_info with key =url"
   },
   { "name": "Interval", "query": "10s,30s,1m,5m,10m,30m,1h" },
   { "name": "container" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "goroutines",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "go_goroutines",
     "query": "SELECT max(\"gauge\") FROM \"go_goroutines\" WHERE $timeFilter GROUP BY time(${Interval}) fill(none)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_mem\" WHERE (\"container_name\" =~ /^$Service$/) AND $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Service$/" }
     ]
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "sys",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "go_memstats_sys_bytes",
     "query": "SELECT mean(\"gauge\") FROM \"process_resident_memory_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Http", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "qps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "go_doudou_http_request_count",
     "query": "SELECT non_negative_derivative(max(\"counter\"), 1s) FROM \"go_doudou_http_request_count\" WHERE $timeFilter GROUP BY time(${Interval}) fill(null)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "timeseries",
   "description": "average response time per Interval time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_method:$tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "go_doudou_http_response_time_seconds",
     "query": "SELECT non_negative_derivative(last(\"sum\")) / non_negative_derivative(last(\"count\")) FROM \"go_doudou_http_response_time_seconds\" WHERE $timeFilter GROUP BY time(${Interval}), \"method\", \"path\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Next GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "next gc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "go_memstats_next_gc_bytes",
     "query": "SELECT mean(\"gauge\") FROM \"go_memstats_next_gc_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg GC Pause",
   "type": "graph",
   "description": "average GC pause time per Interval time",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "go_gc_duration_seconds",
     "query": "SELECT non_negative_derivative(last(\"sum\")) / non_negative_derivative(last(\"count\")) FROM \"go_gc_duration_seconds\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "alias": "gc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "go_gc_duration_seconds",
     "query": "SELECT non_negative_derivative(last(\"count\")) FROM \"go_gc_duration_seconds\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "alias": "0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "go_gc_duration_seconds",
     "query": "SELECT mean(\"0\") FROM \"go_gc_duration_seconds\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "0.25",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "go_gc_duration_seconds",
     "query": "SELECT mean(\"0.25\") FROM \"go_gc_duration_seconds\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
     "select": [
      [
       { "params": [ "0.25" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "0.5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "go_gc_duration_seconds",
     "query": "SELECT mean(\"0.5\") FROM \"go_gc_duration_seconds\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
     "select": [
      [
       { "params": [ "0.5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "0.75",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "go_gc_duration_seconds",
     "query": "SELECT mean(\"0.75\") FROM \"go_gc_duration_seconds\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
     "select": [
      [
       { "params": [ "0.75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "go_gc_duration_seconds",
     "query": "SELECT mean(\"1\") FROM \"go_gc_duration_seconds\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap Objects (total number of allocated objects)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "count" }
     ],
     "targets": [
      {
       "alias": "objects",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "go_memstats_heap_objects",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_heap_objects\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Overall Heap usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes", "label": "count" }
     ],
     "targets": [
      {
       "alias": "HeapAlloc (bytes of allocated heap objects)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "go_memstats_heap_alloc_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_heap_alloc_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "HeapSys (bytes of heap memory obtained from the OS)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "go_memstats_heap_sys_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_heap_sys_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "HeapIdle (bytes in unused spans)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_heap_idle_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_heap_idle_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "HeapInuse (bytes in in-use spanse)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_heap_inuse_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_heap_inuse_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "HeapReleased (bytes of physical memory returned to the OS)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_heap_released_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_heap_released_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mallocs and frees",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "malloc",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "go_memstats_mallocs_total",
       "query": "SELECT mean(\"counter\") FROM \"go_memstats_mallocs_total\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "free",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_frees_total",
       "query": "SELECT mean(\"counter\") FROM \"go_memstats_frees_total\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TotalAlloc (bytes allocated even if freed)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "alias": "total allocations",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "go_memstats_alloc_bytes_total",
       "query": "SELECT mean(\"counter\") FROM \"go_memstats_alloc_bytes_total\" WHERE $timeFilter GROUP BY time($Interval) fill(none)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Stack memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "StackInUse (bytes in stack spans)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_stack_inuse_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_stack_inuse_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "StackSys (bytes of stack memory obtained from OS)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_stack_sys_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_stack_sys_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "MSpanInuse (bytes of allocated mspan structures)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_mspan_inuse_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_mspan_inuse_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "MSpanSys (bytes of memory obtained from the OS for mspan)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_mspan_sys_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_mspan_sys_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "MCacheInuse (bytes of allocated mcache structures)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_mcache_inuse_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_mcache_inuse_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "MCacheSys (bytes of memory obtained from the OS for mcache structures)",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_mcache_sys_bytes",
       "query": "SELECT mean(\"gauge\") FROM \"go_memstats_mcache_sys_bytes\" WHERE $timeFilter GROUP BY time($Interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}