// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.

package dto

// ProductType mapped from table <product_type>
type ProductType struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id,omitempty"`
	Title       *string `gorm:"column:title;type:varchar(100);comment:标题" json:"title,omitempty"`             // 标题
	Description *string `gorm:"column:description;type:varchar(500);comment:描述" json:"description,omitempty"` // 描述
	Status      *int32  `gorm:"column:status;type:tinyint(4);comment:状态" json:"status,omitempty"`             // 状态
	AddTime     *int32  `gorm:"column:add_time;type:int(10);comment:添加时间" json:"addTime,omitempty"`           // 添加时间
}
