// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.

package dto

//go:generate go-doudou name --file $GOFILE

// QrtzBlobTrigger mapped from table <qrtz_blob_triggers>
type QrtzBlobTrigger struct {
	SCHEDNAME    string `json:"sCHEDNAME"`
	TRIGGERNAME  string `json:"tRIGGERNAME"`
	TRIGGERGROUP string `json:"tRIGGERGROUP"`
	BLOBDATA     []byte `json:"bLOBDATA"`
}
