// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.
// Code generated by gorm.io/gen. YOU CAN EDIT.

package dto

import (
	"time"
)

//go:generate go-doudou name --file $GOFILE

// TUser mapped from table <t_user>
type TUser struct {
	ID       int32      `json:"id"`
	Username string     `json:"username"` // username
	Password string     `json:"password"` // password
	Name     string     `json:"name"`     // real name
	Phone    string     `json:"phone"`    // phone number
	Dept     string     `json:"dept"`     // department
	Avatar   string     `json:"avatar"`   // user avatar
	CreateAt *time.Time `json:"createAt"`
	UpdateAt *time.Time `json:"updateAt"`
	DeleteAt time.Time  `json:"deleteAt"`
}
