/**
* Generated by go-doudou v2.0.3.
* You can edit it as your need.
 */
package vo

//go:generate go-doudou name --file $GOFILE

type Service struct {
	Name     string `json:"name"`
	RpcAddr  string `json:"rpcAddr"`
	RestAddr string `json:"restAddr"`
	Weight   int    `json:"weight"`
}
